/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klijent.forme;

import zajednicki.domen.Users;
import zajednicki.konstante.Operacije;
import klijent.kontroler.Komunikacija;
import zajednicki.transfer.KlijentskiZahtev;
import zajednicki.transfer.PasswordUtill;
import zajednicki.transfer.ServerskiOdgovor;

import javax.swing.*;

/**
 *
 * @author Marija
 */
public class PasswordForm extends javax.swing.JFrame {

    /**
     * Creates new form PasswordForm
     */
    Users ulogovani;

    public PasswordForm(Users ulogovani) {
        initComponents();
        Placeholer.dodajPlaceholder(txtCurrent, "Password1#");
        Placeholer.dodajPlaceholder(txtNew, "Password2#");
        Placeholer.dodajPlaceholder(txtConfirm, "Password2#");
        setLocationRelativeTo(null);
        setTitle("Password Form");
        setResizable(false);
        CustomOptionPane cop = new CustomOptionPane();
        btnIzmeni.requestFocusInWindow();

        this.ulogovani = ulogovani;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCurrent = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtNew = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        btnIzmeni = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 435));
        setSize(new java.awt.Dimension(500, 435));

        jPanel1.setBackground(new java.awt.Color(255, 198, 224));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 435));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel1.setText("Password");
        jLabel1.setPreferredSize(new java.awt.Dimension(114, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel2.setText("Current password:");
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 30));

        txtCurrent.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtCurrent.setMinimumSize(new java.awt.Dimension(400, 30));
        txtCurrent.setSelectionColor(new java.awt.Color(255, 198, 224));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel3.setText("New password:");
        jLabel3.setPreferredSize(new java.awt.Dimension(400, 30));

        txtNew.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        txtNew.setPreferredSize(new java.awt.Dimension(400, 30));
        txtNew.setSelectionColor(new java.awt.Color(255, 198, 224));
        txtNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel4.setText("Confirm new password:");
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 30));

        txtConfirm.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtConfirm.setPreferredSize(new java.awt.Dimension(400, 30));
        txtConfirm.setSelectionColor(new java.awt.Color(255, 198, 224));

        btnIzmeni.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        btnIzmeni.setText("Change");
        btnIzmeni.setPreferredSize(new java.awt.Dimension(200, 30));
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnNazad.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnNazad.setText("Back");
        btnNazad.setPreferredSize(new java.awt.Dimension(150, 30));
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(150, 150, 150)
                                                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(175, 175, 175)
                                                .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        String current = String.valueOf(txtCurrent.getPassword());
        String neew = String.valueOf(txtNew.getPassword());
        String confirm = String.valueOf(txtConfirm.getPassword());

        String greska = validacija();

        if (!greska.equals("")) {
            JOptionPane.showMessageDialog(this, greska);
            return;
        }

        //Prvo moram da proverim da li se Password poklapa sam passwordom iz baze
        Users u = new Users();
        u.setUserID(ulogovani.getUserID());
        u.setPassword(current);

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_PASSWORD);
        kz.setParametar(u);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        boolean ispravanPassword = (boolean) so.getOdgovor();

        if (!ispravanPassword) {
            Object[] opcije = {"Try again", "Exit"};
            int izbor = JOptionPane.showOptionDialog(this, "Current password je pogresan!", "Information Form", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opcije, opcije[1]);
            switch (izbor) {
                case 0:
                    txtCurrent.setText("");
                    txtNew.setText("");
                    txtConfirm.setText("");
                    break;
                case 1:
                    this.dispose();
                    break;
            }
            return;
        }

        //Kada svi uneti podaci budu odgovarajuci i prodju validaciju, ja ih pokupim iz forme i lozinku hesujem i takvu dalje prosledjujem
        String hashNewPassword = PasswordUtill.hesujLozinku(neew);

        Users user = new Users();
        user.setUserID(ulogovani.getUserID());
        user.setPassword(hashNewPassword);

        KlijentskiZahtev kz1 = new KlijentskiZahtev();
        kz1.setOperacija(Operacije.IZMENI_PASSWORD);
        kz1.setParametar(user);

        Komunikacija.getInstance().posaljiZahtev(kz1);
        ServerskiOdgovor so1 = Komunikacija.getInstance().primiOdgovor();

        boolean uspesnoIzmenjenPassword = (boolean) so1.getOdgovor();

        if (!uspesnoIzmenjenPassword) {
            Object[] opcije = {"Try again", "Exit"};
            int izbor = JOptionPane.showOptionDialog(this, "Doslo je do greske prilikom izmene lozinke!", "Information Form", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opcije, opcije[1]);
            switch (izbor) {
                case 0:
                    txtCurrent.setText("");
                    txtNew.setText("");
                    txtConfirm.setText("");
                    break;
                case 1:
                    this.dispose();
                    break;
            }
            return;
        }

        JOptionPane.showMessageDialog(this, "Uspesno ste izmenili lozinku!");
        this.dispose();
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnNazad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JPasswordField txtCurrent;
    private javax.swing.JPasswordField txtNew;
    // End of variables declaration//GEN-END:variables

    private String validacija() {
        String current = String.valueOf(txtCurrent.getPassword());
        String neew = String.valueOf(txtNew.getPassword());
        String confirm = String.valueOf(txtConfirm.getPassword());
        String greska = "";


        //Proveravam da li su sva polja popunjena
        if (current.isEmpty() || neew.isEmpty() || confirm.isEmpty() ||
                current.equals("Password1#") || neew.equals("Password2#") || confirm.equals("Password2#")) {
            greska += "Morate popuniti sva polja!";
            return greska;
        }

        //Proveravam da li lozinka pocinje velikim slovom
        if (!Character.isUpperCase(neew.charAt(0))) {
            greska += "Lozinka mora poceti velikim slovom!";
            return greska;
        }

        //Proveravam da li lozinka sadrzi bar jedan broj
        if (!sadrziBroj(neew)) {
            greska += "Lozinka mora da sadrzi bar jedan broj!";
            return greska;
        }

        //Proveravam da li lozinka sadrzi bar jedan specijalni karakter
        if (!sadrziSpecijalniKarakter(neew)) {
            greska += "Lozinka mora da sadrzi bar jedan specijalni karakter!";
            return greska;
        }

        if (!sadrziBarOsamKaraktera(neew)) {
            greska += "Lozinka mora da sadrzi bar 8 karaktera!";
            return greska;
        }

        //Proveravam da li lozinka i potvrda lozinke imaju iste vrednosti
        if (!(neew.equals(confirm))) {
            greska += "New password i Confirm password moraju da imaju iste vrednosti!";
            return greska;
        }

        //Proveravam da li su stara i nova lozinka iste 
        if (current.equals(neew)) {
            greska += "New password ne sme biti ista kao Current password!";
            return greska;
        }

        return greska;
    }


    private boolean sadrziBroj(String string) {
        for (Character karakter : string.toCharArray()) {
            if (Character.isDigit(karakter)) {
                return true;
            }
        }
        return false;
    }

    private boolean sadrziSpecijalniKarakter(String string) {
        for (Character karakter : string.toCharArray()) {
            if (!Character.isLetterOrDigit(karakter)) {
                return true;
            }
        }
        return false;
    }


    private boolean sadrziBarOsamKaraktera(String string) {
        return string.length() >= 8;
    }

}
