/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klijent.forme;

import zajednicki.domen.Users;
import zajednicki.konstante.Operacije;
import klijent.kontroler.Komunikacija;
import zajednicki.transfer.KlijentskiZahtev;
import zajednicki.transfer.PasswordUtill;
import zajednicki.transfer.ServerskiOdgovor;

import javax.swing.*;

/**
 *
 * @author Marija
 */
public class SingUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SingUpForm
     */
    public SingUpForm() {
        initComponents();
        Placeholer.dodajPlaceholder(txtFirstName, "Name");
        Placeholer.dodajPlaceholder(txtLastName, "Surename");
        Placeholer.dodajPlaceholder(txtEmail, "email@gmail.com");
        Placeholer.dodajPlaceholder(txtPassword, "Password1#");
        Placeholer.dodajPlaceholder(txtConfirm, "Password1#");
        setLocationRelativeTo(null);
        setTitle("Sing up Form");
        setResizable(false);
        CustomOptionPane cop = new CustomOptionPane();
        btnSingUp.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        btnSingIn = new javax.swing.JButton();
        btnSingUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 550));

        jPanel1.setBackground(new java.awt.Color(255, 198, 224));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel6.setText("                               Sing up");
        jLabel6.setPreferredSize(new java.awt.Dimension(500, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 198, 224));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel1.setText("First name:");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 30));

        txtFirstName.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtFirstName.setPreferredSize(new java.awt.Dimension(400, 30));
        txtFirstName.setSelectionColor(new java.awt.Color(255, 198, 224));
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel2.setText("Last name:");
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 30));

        txtLastName.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtLastName.setPreferredSize(new java.awt.Dimension(400, 30));
        txtLastName.setSelectionColor(new java.awt.Color(255, 198, 224));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel3.setText("Email:");
        jLabel3.setPreferredSize(new java.awt.Dimension(400, 30));

        txtEmail.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(100, 30));
        txtEmail.setSelectionColor(new java.awt.Color(255, 198, 224));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel4.setText("Password:");
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 30));

        txtPassword.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(400, 30));
        txtPassword.setSelectionColor(new java.awt.Color(255, 198, 224));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel5.setText("Confirm password:");
        jLabel5.setPreferredSize(new java.awt.Dimension(400, 30));

        txtConfirm.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtConfirm.setPreferredSize(new java.awt.Dimension(400, 30));
        txtConfirm.setSelectionColor(new java.awt.Color(255, 198, 224));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnSingIn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSingIn.setText("Sing in");
        btnSingIn.setPreferredSize(new java.awt.Dimension(150, 30));
        btnSingIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingInActionPerformed(evt);
            }
        });

        btnSingUp.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        btnSingUp.setText("Sing up");
        btnSingUp.setPreferredSize(new java.awt.Dimension(200, 30));
        btnSingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(150, 150, 150)
                                                .addComponent(btnSingUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(175, 175, 175)
                                                .addComponent(btnSingIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSingUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSingIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnSingInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingInActionPerformed
        SingInForm sif = new SingInForm();
        sif.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSingInActionPerformed

    private void btnSingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingUpActionPerformed
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String email = txtEmail.getText();
        String password = String.valueOf(txtPassword.getPassword());

        String greska = validacija();

        if (!greska.equals("")) {
            JOptionPane.showMessageDialog(this, greska);
            return;
        }

        //Kada svi uneti podaci budu odgovarajuci i prodju validaciju, ja ih pokupim iz forme i lozinku hesujem i takvu dalje prosledjujem
        String hashPassword = PasswordUtill.hesujLozinku(password);

        Users user = new Users(-1, firstName, lastName, email, hashPassword, null, null);

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.SINGUP);
        kz.setParametar(user);

        Komunikacija.getInstance().posaljiZahtev(kz);

        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        boolean uspesnoRegistovan = (boolean) so.getOdgovor();

        if (!uspesnoRegistovan) {
            Object[] opcije = {"Try again", "Exit"};
            int izbor = JOptionPane.showOptionDialog(this, "Doslo je do greske prilikom registracije, vec postoji korisnik sa ovom email adresom!", "Information Form", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opcije, opcije[1]);
            switch (izbor) {
                case 0:
                    srediFormu();
                    break;
                case 1:
                    this.dispose();
                    break;
                default:
                    return;
            }
            return;
        }
        JOptionPane.showMessageDialog(this, "Registracija uspesno obavljena!");
        SingInForm sif = new SingInForm();
        sif.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnSingUpActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSingIn;
    private javax.swing.JButton btnSingUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private String validacija() {
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String email = txtEmail.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String confirm = String.valueOf(txtConfirm.getPassword());
        String greska = "";


        //Proveravam da li su sva polja popunjena
        if (firstName.isEmpty() || lastName.isEmpty() || email.isEmpty() || password.isEmpty() || confirm.isEmpty() ||
                firstName.equals("Name") || lastName.equals("Surename") || email.equals("email@gmail.com") ||
                password.equals("Password1#") || confirm.equals("Password1#")) {
            greska += "Morate popuniti sva polja!";
            return greska;
        }

        //Proveravam da li ime sadrzi samo slova
        if (!!sadrziSamoSlova(firstName)) {
            greska += "Ime mora da sadrzi samo slova!";
            return greska;
        }

        //Proveravam da li ime pocinje velikim slovom
        if (!Character.isUpperCase(firstName.charAt(0))) {
            greska += "Ime mora poceti velikim slovom!";
            return greska;
        }

        //Proveravam da li sva slova(sem prvog) mala u imenu
        for (Character ime : firstName.substring(1).toCharArray()) {
            if (!Character.isLowerCase(ime)) {
                greska += "Samo prvo slovo imena je veliko, ostala su mala";
                break;
            }
        }

        //Proveravam da li prezime sadrzi samo slova
        if (!!sadrziSamoSlova(lastName)) {
            greska += "Prezime mora da sadrzi samo slova!";
            return greska;
        }

        //Proveravam da li prezime pocinje velikim slovom
        if (!Character.isUpperCase(lastName.charAt(0))) {
            greska += "Prezime mora poceti velikim slovom!";
            return greska;
        }

        //Proveravam da li sva slova(sem prvog) mala u prezimenu
        for (Character prezime : lastName.substring(1).toCharArray()) {
            if (!Character.isLowerCase(prezime)) {
                greska += "Samo prvo slovo prezimena je veliko, ostala su mala";
                break;
            }
        }

        //Proveravam da li je email u dobrom formatu
        if (!validanEmail(email)) {
            greska += "Email nije u dobrom formatu!";
            return greska;
        }

        //Proveravam da li lozinka pocinje velikim slovom
        if (!Character.isUpperCase(password.charAt(0))) {
            greska += "Lozinka mora poceti velikim slovom!";
            return greska;
        }

        //Proveravam da li lozinka sadrzi bar jedan broj
        if (!sadrziBroj(password)) {
            greska += "Lozinka mora da sadrzi bar jedan broj!";
            return greska;
        }

        //Proveravam da li lozinka sadrzi bar jedan specijalni karakter
        if (!sadrziSpecijalniKarakter(password)) {
            greska += "Lozinka mora da sadrzi bar jedan specijalni karakter!";
            return greska;
        }

        //Proveravam da li lozinka sadrzi bar 8 karaktera
        if (!sadrziBarOsamKaraktera(password)) {
            greska += "Lozinka mora da sadrzi bar 8 karaktera!";
            return greska;
        }

        //Proveravam da li lozinka i potvrda lozinke imaju iste vrednosti
        if (!(password.equals(confirm))) {
            greska += "Password i Confirm password moraju da imaju iste vrednosti!";
            return greska;
        }

        return greska;
    }

    private boolean sadrziSamoSlova(String string) {
        for (Character karakter : string.toCharArray()) {
            if (!Character.isLetter(karakter)) {
                return true;
            }
        }
        return false;
    }

    private boolean sadrziBroj(String string) {
        for (Character karakter : string.toCharArray()) {
            if (Character.isDigit(karakter)) {
                return true;
            }
        }
        return false;
    }

    private boolean sadrziSpecijalniKarakter(String string) {
        for (Character karakter : string.toCharArray()) {
            if (!Character.isLetterOrDigit(karakter)) {
                return true;
            }
        }
        return false;
    }


    private boolean sadrziBarOsamKaraktera(String string) {
        return string.length() >= 8;
    }

    private boolean validanEmail(String email) {
        String validanEmail = "^[a-z](?!.*\\.\\.)[A-Za-z0-9!#$%&'*+/=?^_`{|}~.-]*@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";

        return email.matches(validanEmail);
    }

    private void srediFormu() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
        txtConfirm.setText("");
    }


}
