/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;
import domen.Entries;
import domen.Groups;
import domen.Users;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import konstante.Operacije;
import kontroler.Komunikacija;
import modeli.ModelTableEntries;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;
import transfer.TreeRenderer;
import transfer.ZahtevZaEntrije;

/**
 *
 * @author Marija
 */
public class KlijentskaForma extends javax.swing.JFrame {

    /**
     * Creates new form ClientForm
     */    
    Users ulogovani;
    
    public KlijentskaForma(Users user) {
        initComponents();
        setTitle("Client Form");
        setLocationRelativeTo(null);
        setResizable(false);
        toolBar.setFloatable(false);
        tblEntries.getTableHeader().setFont(new Font("Arial Black", Font.BOLD, 14));
        btnPretrazi.requestFocusInWindow();
        Placeholer.dodajPlaceholder(txtPretraga, "Text...");
        CustomOptionPane cop=new CustomOptionPane();
        
        this.ulogovani=user;
        
        //root - glavni cvor u stablu, true - znaci da ima decu(da mi izgleda kao folder)
        DefaultMutableTreeNode root=new DefaultMutableTreeNode(ulogovani, true);
        //kreiram model za moj root
        DefaultTreeModel model=new DefaultTreeModel(root);
        //drvu dodajem model
        jTree1.setModel(model);
        jTree1.setCellRenderer(new TreeRenderer());
        
        //popunjavam ostale cvorove u stablu
        popuniStablo();
        
        ModelTableEntries mt=new ModelTableEntries(ulogovani, new ArrayList<>());
        tblEntries.setModel(mt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        btnNalog = new javax.swing.JButton();
        btnKreirajGrupu = new javax.swing.JButton();
        btnKreirajUnos = new javax.swing.JButton();
        btnIzmeniGrupu = new javax.swing.JButton();
        btnIzmeniUnos = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnSingOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEntries = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        txtPretraga = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        jPanel3.setBackground(new java.awt.Color(255, 198, 224));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 500));

        toolBar.setBackground(new java.awt.Color(255, 255, 255));
        toolBar.setRollover(true);
        toolBar.setPreferredSize(new java.awt.Dimension(800, 50));

        btnNalog.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnNalog.setText("Account");
        btnNalog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNalog.setPreferredSize(new java.awt.Dimension(70, 40));
        btnNalog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNalogActionPerformed(evt);
            }
        });
        toolBar.add(btnNalog);

        btnKreirajGrupu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnKreirajGrupu.setText("Create group");
        btnKreirajGrupu.setPreferredSize(new java.awt.Dimension(120, 40));
        btnKreirajGrupu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajGrupuActionPerformed(evt);
            }
        });
        toolBar.add(btnKreirajGrupu);

        btnKreirajUnos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnKreirajUnos.setText("Create entry");
        btnKreirajUnos.setPreferredSize(new java.awt.Dimension(120, 40));
        btnKreirajUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajUnosActionPerformed(evt);
            }
        });
        toolBar.add(btnKreirajUnos);

        btnIzmeniGrupu.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnIzmeniGrupu.setText("Update group");
        btnIzmeniGrupu.setPreferredSize(new java.awt.Dimension(125, 40));
        btnIzmeniGrupu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniGrupuActionPerformed(evt);
            }
        });
        toolBar.add(btnIzmeniGrupu);

        btnIzmeniUnos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnIzmeniUnos.setText("Update entry");
        btnIzmeniUnos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIzmeniUnos.setPreferredSize(new java.awt.Dimension(125, 40));
        btnIzmeniUnos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIzmeniUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniUnosActionPerformed(evt);
            }
        });
        toolBar.add(btnIzmeniUnos);

        btnObrisi.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnObrisi.setText("Delete group/entry");
        btnObrisi.setPreferredSize(new java.awt.Dimension(150, 40));
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });
        toolBar.add(btnObrisi);

        btnSingOut.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSingOut.setText("Sing out");
        btnSingOut.setPreferredSize(new java.awt.Dimension(70, 40));
        btnSingOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingOutActionPerformed(evt);
            }
        });
        toolBar.add(btnSingOut);

        jTree1.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jTree1.setForeground(new java.awt.Color(0, 0, 0));
        jTree1.setPreferredSize(new java.awt.Dimension(150, 400));
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jScrollPane2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 400));
        jScrollPane2.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(null);

        tblEntries.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        tblEntries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEntries.setFillsViewportHeight(true);
        tblEntries.setGridColor(new java.awt.Color(255, 198, 224));
        tblEntries.setPreferredSize(new java.awt.Dimension(640, 300));
        tblEntries.setSelectionBackground(new java.awt.Color(255, 198, 224));
        tblEntries.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblEntries);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 50));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel1.setText("Home");
        jLabel1.setPreferredSize(new java.awt.Dimension(66, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnPretrazi.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnPretrazi.setText("Search");
        btnPretrazi.setPreferredSize(new java.awt.Dimension(200, 40));
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        txtPretraga.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        txtPretraga.setPreferredSize(new java.awt.Dimension(300, 40));
        txtPretraga.setSelectionColor(new java.awt.Color(255, 198, 224));
        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSingOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingOutActionPerformed
        int result=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if(result==JOptionPane.NO_OPTION){
            return;
        }

        if(result==JOptionPane.YES_OPTION){
            KlijentskiZahtev kz=new KlijentskiZahtev();
            kz.setOperacija(Operacije.SINGOUT);
            kz.setParametar(ulogovani.getUserID());

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so=Komunikacija.getInstance().primiOdgovor();

            boolean uspesnoOdjavljen=(boolean) so.getOdgovor();

            if(uspesnoOdjavljen){
                JOptionPane.showMessageDialog(this, "Uspesno ste se odjavili sa sistema!");
                System.exit(0);
            } else{
                JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom odjve...");
            }

        }
    }//GEN-LAST:event_btnSingOutActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        DefaultMutableTreeNode listCvor=(DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();

        if(listCvor==null){
            return;
        }

        Object obj=listCvor.getUserObject();
        ModelTableEntries mt=(ModelTableEntries) tblEntries.getModel();

        if(obj instanceof Entries selektovanEntry){
            mt.prikaziSelektovanEntry(selektovanEntry);
        }else if(obj instanceof Groups selektovanaGrupa){
            mt.prikaziEntrijeZaGrupu(selektovanaGrupa);
        } else{
            mt.ocistiTabelu();
        }
    }//GEN-LAST:event_jTree1ValueChanged

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        DefaultMutableTreeNode listCvor=(DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();

        if(listCvor==null){
            JOptionPane.showMessageDialog(this, "Morate selektovati ono sto zelite da obrisete!");
            return;
        }

        int rezultat=JOptionPane.showConfirmDialog(this,"Da li ste sigurni da zelite da obrisete unos/grupu?", "Konfirmacija", JOptionPane.YES_NO_OPTION);
        if(rezultat==JOptionPane.NO_OPTION){
            return;
        }

        Object obj=listCvor.getUserObject();
        ModelTableEntries mt=(ModelTableEntries) tblEntries.getModel();

        if(obj instanceof Entries selektovanEntry){
            KlijentskiZahtev kz=new KlijentskiZahtev();
            kz.setOperacija(Operacije.OBRISI_ENTRY);
            kz.setParametar(selektovanEntry);

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so=Komunikacija.getInstance().primiOdgovor();

            boolean uspesnoObrisanEntry=(boolean) so.getOdgovor();

            if(!uspesnoObrisanEntry){
                JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom brisanja!");
                return;
            }

            JOptionPane.showMessageDialog(this, "Uspesno ste obrisali unos!");
            SwingUtilities.invokeLater(()->{
                popuniStablo();
                mt.ocistiTabelu();
            });

        }
        if(obj instanceof Groups selektovanaGrupa){
            KlijentskiZahtev kz=new KlijentskiZahtev();
            kz.setOperacija(Operacije.OBRISI_GRUPU);
            kz.setParametar(new ZahtevZaEntrije(selektovanaGrupa, ulogovani));

            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so=Komunikacija.getInstance().primiOdgovor();

            boolean uspesnoObrisanaGrupa=(boolean) so.getOdgovor();

            if(!uspesnoObrisanaGrupa){
                JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom brisanja!");
                return;
            }

            JOptionPane.showMessageDialog(this, "Uspesno ste obrisali unos!");
            SwingUtilities.invokeLater(()->{
                popuniStablo();
                mt.ocistiTabelu();
            });
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmeniGrupuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniGrupuActionPerformed
        DefaultMutableTreeNode cvor=(DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        if(cvor==null){
            JOptionPane.showMessageDialog(this,"Morate selektovati grupu!");
            return;
        }
        
        Object obj=cvor.getUserObject();
        if(obj instanceof Groups){
            Groups selektovanaGrupa=(Groups) obj;    
            UpdateGroupForm ugf=new UpdateGroupForm(selektovanaGrupa);
            ugf.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent e){
                popuniStablo();
                jTree1.clearSelection();
                tblEntries.setModel(new ModelTableEntries(ulogovani, new ArrayList<>()));
            }
        });
            ugf.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(this, "Morate selektovati grupu!");
        }
    }//GEN-LAST:event_btnIzmeniGrupuActionPerformed

    private void btnKreirajUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajUnosActionPerformed
        CreateEntryForm cef=new CreateEntryForm(ulogovani);
        cef.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent e){
                popuniStablo();
                jTree1.clearSelection();
                tblEntries.setModel(new ModelTableEntries(ulogovani, new ArrayList<>()));
            }
        });

        cef.setVisible(true);
    }//GEN-LAST:event_btnKreirajUnosActionPerformed

    private void btnKreirajGrupuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajGrupuActionPerformed
        CreateGroupForm cgf=new CreateGroupForm(ulogovani);
        cgf.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent e){
                popuniStablo();
                jTree1.clearSelection();
                tblEntries.setModel(new ModelTableEntries(ulogovani, new ArrayList<>()));
            }
        });

        cgf.setVisible(true);
    }//GEN-LAST:event_btnKreirajGrupuActionPerformed

    private void btnNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNalogActionPerformed
        AccountForm af=new AccountForm(ulogovani);
        af.setVisible(true);
    }//GEN-LAST:event_btnNalogActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
         String text=txtPretraga.getText().trim().toLowerCase();
         
         if(text.isEmpty() || text.equals("text...")){
             JOptionPane.showMessageDialog(this, "Morate uneti tekst koji zelite da pretrazite!");
             tblEntries.setModel(new ModelTableEntries(ulogovani, new ArrayList<>()));
             jTree1.clearSelection();
             return;
         }
         
         ArrayList<Entries> rezultat=new ArrayList<>();

         DefaultMutableTreeNode root=(DefaultMutableTreeNode) jTree1.getModel().getRoot();
         
         pretraziStablo(root, text, rezultat);
         
         if(rezultat.isEmpty()){
             JOptionPane.showMessageDialog(this, "Nema rezultata za: "+text);
             tblEntries.setModel(new ModelTableEntries(ulogovani, new ArrayList<>()));
             return;
         }
         
         tblEntries.setModel(new ModelTableEntries(ulogovani,rezultat));
         
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnIzmeniUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniUnosActionPerformed
        DefaultMutableTreeNode cvor=(DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        if(cvor==null){
            JOptionPane.showMessageDialog(this,"Morate selektovati entry!");
            return;
        }
        
        Object obj=cvor.getUserObject();
        if(obj instanceof Entries){
            Entries selektovaniEntry=(Entries) obj;    
            UpdateEntryForm uef=new UpdateEntryForm(selektovaniEntry);
            uef.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent e){
                popuniStablo();
                jTree1.clearSelection();
                tblEntries.setModel(new ModelTableEntries(ulogovani, new ArrayList<>()));
            }
        });
            uef.setVisible(true);
        } else{
            JOptionPane.showMessageDialog(this, "Morate selektovati entry!");
        }
    }//GEN-LAST:event_btnIzmeniUnosActionPerformed

    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniGrupu;
    private javax.swing.JButton btnIzmeniUnos;
    private javax.swing.JButton btnKreirajGrupu;
    private javax.swing.JButton btnKreirajUnos;
    private javax.swing.JButton btnNalog;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnSingOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JTable tblEntries;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void popuniStablo() {
        //prvo vracam sve grupe za korisnika
        KlijentskiZahtev kz=new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_GRUPE);
        kz.setParametar(ulogovani);
        
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so=Komunikacija.getInstance().primiOdgovor();
        
        ArrayList<Groups> grupe=(ArrayList<Groups>) so.getOdgovor();
        
        DefaultTreeModel model=(DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode root=(DefaultMutableTreeNode) model.getRoot();
        
        root.removeAllChildren();
        
        for(Groups g: grupe){
            DefaultMutableTreeNode cvor=new DefaultMutableTreeNode(g, true);
            
            //Za svaku grupu koja ima entry dodajem ga
            KlijentskiZahtev kz2=new KlijentskiZahtev();
            kz2.setOperacija(Operacije.VRATI_ENTRIJE_ZA_GRUPU);
            kz2.setParametar(new ZahtevZaEntrije(g, ulogovani));
            
            Komunikacija.getInstance().posaljiZahtev(kz2);
            ServerskiOdgovor so2=Komunikacija.getInstance().primiOdgovor();
            
            ArrayList<Entries> entriesG=(ArrayList<Entries>) so2.getOdgovor();
            
            for(Entries e: entriesG){
                DefaultMutableTreeNode list=new DefaultMutableTreeNode(e, false);
                cvor.add(list);
            }        
            root.add(cvor);
        }
        
        KlijentskiZahtev kz3=new KlijentskiZahtev();
        kz3.setOperacija(Operacije.VRATI_ENTRIJE_BEZ_GRUPA);
        kz3.setParametar(ulogovani);
        
        Komunikacija.getInstance().posaljiZahtev(kz3);
        ServerskiOdgovor so3=Komunikacija.getInstance().primiOdgovor();
        
        ArrayList<Entries> entries=(ArrayList<Entries>) so3.getOdgovor();
        
        for(Entries e: entries){
                DefaultMutableTreeNode list=new DefaultMutableTreeNode(e, false);
                root.add(list);
        }
                
        model.reload();
    }

    
    private void  pretraziStablo(DefaultMutableTreeNode root, String text, ArrayList<Entries> rezultat){
        if(root==null){
            return;
        }
        
        Object obj=root.getUserObject();
        
        if(obj instanceof Entries entry){
            String lower=text.toLowerCase();
            if(text.isEmpty()||
               entry.getTitle().toLowerCase().contains(lower) ||
               entry.getUsername().toLowerCase().contains(lower) ||
               entry.getUrl().toLowerCase().contains(lower) ||
               entry.getNote().toLowerCase().contains(lower)){
                 rezultat.add(entry);
            }
        }
        
        Enumeration<?> children=root.children();
        while(children.hasMoreElements()){
            DefaultMutableTreeNode child=(DefaultMutableTreeNode) children.nextElement(); 
            pretraziStablo(child, text, rezultat);
        }
    
    }
}
